### ISSUE TITLE
Error using resnet50-fpn backbone

### ISSUE THREAD

**Issue by Mansoor-at** [AlphaJia/pytorch-faster-rcnn#17]
Hi
I am getting following error if i use resnet50-fpn backbone. mobilenet just works fine. Could you help me. 

Traceback (most recent call last):
  File "/Users/Mansoor/PycharmProjects/pythonProject/train.py", line 131, in <module>
    main()
  File "/Users/Mansoor/PycharmProjects/pythonProject/train.py", line 83, in main
    print_freq=50, warmup=False)
  File "/Users/Mansoor/PycharmProjects/pythonProject/utils/train_utils.py", line 373, in train_one_epoch
    loss_dict = model(images, targets)
  File "/Users/Mansoor/opt/anaconda3/envs/pythonProject/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/Mansoor/PycharmProjects/pythonProject/utils/faster_rcnn_utils.py", line 85, in forward
    proposals, proposal_losses = self.rpn(images, features, targets)
  File "/Users/Mansoor/opt/anaconda3/envs/pythonProject/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/Mansoor/PycharmProjects/pythonProject/utils/rpn_utils.py", line 290, in forward
    proposals = self.box_coder.decode(pred_bbox_deltas.detach(), anchors)
  File "/Users/Mansoor/PycharmProjects/pythonProject/utils/det_utils.py", line 182, in decode
    rel_codes.reshape(box_sum, -1), concat_boxes
RuntimeError: shape '[96768, -1]' is invalid for input of size 392832

**Comment by Ayu000** [comment]
I changed anchor_size from [64, 128, 256] to [32, 64, 128, 256, 512] in train_config.py

**Comment by TrinhThiBaoAnh** [comment]
> I changed anchor_size from [64, 128, 256] to [32, 64, 128, 256, 512] in train_config.py

Thanks so much! But i still don't understand the reason for this! Can you explain more ?
